server {
    listen 80;
    server_name _;
    client_max_body_size 8m;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    include /etc/nginx/portfolio/proxy.inc;
}
